### ISSUE TITLE
How to run the script as Administrator?

### ISSUE THREAD

**Issue by JohnFortniteKennedy-skrt** [exex4/xx4-bfv-aimassist#6]
Title

**Comment by DJPatron** [comment]
Create .bat file with random name, such as aim.bat, then copypaste into it:
```
powershell -Command "Start-Process 'python' -Verb runAs -ArgumentList 'assist.py 640 480'"
@if NOT ["%errorlevel%"]==["0"] pause
```
Save file.
Then rightclick to this .bat, click Properties then go to compatibility tab and check "Run as administrator".
When you start this .bat, UAC prompt window will appear, click "yes".
This description of menu items may be inaccurate because of my Windows OS localization is set to Russian.

**Comment by mon5termatt** [comment]
personally i use this script, no need for changing the script to run as admin.

```@echo off
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )
:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
    "%temp%\getadmin.vbs"
    exit /B
:gotAdmin
    if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
    pushd "%CD%"
    CD /D "%~dp0"
cls
python assist.py```

**Comment by mon5termatt** [comment]
[start.bat.txt](https://github.com/exex4/xx4-bfv-aimassist/files/5580881/start.bat.txt)

DOWNLOAD AND REMOVE .TXT
